set(_CATKIN_CURRENT_PACKAGE "play_drive")
set(play_drive_VERSION "0.0.0")
set(play_drive_MAINTAINER "hansung <hansung@todo.todo>")
set(play_drive_PACKAGE_FORMAT "2")
set(play_drive_BUILD_DEPENDS )
set(play_drive_BUILD_EXPORT_DEPENDS )
set(play_drive_BUILDTOOL_DEPENDS "catkin")
set(play_drive_BUILDTOOL_EXPORT_DEPENDS )
set(play_drive_EXEC_DEPENDS )
set(play_drive_RUN_DEPENDS )
set(play_drive_TEST_DEPENDS )
set(play_drive_DOC_DEPENDS )
set(play_drive_URL_WEBSITE "")
set(play_drive_URL_BUGTRACKER "")
set(play_drive_URL_REPOSITORY "")
set(play_drive_DEPRECATED "")