set(_CATKIN_CURRENT_PACKAGE "detect_person")
set(detect_person_VERSION "0.0.0")
set(detect_person_MAINTAINER "hansung <hansung@todo.todo>")
set(detect_person_PACKAGE_FORMAT "2")
set(detect_person_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(detect_person_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(detect_person_BUILDTOOL_DEPENDS "catkin")
set(detect_person_BUILDTOOL_EXPORT_DEPENDS )
set(detect_person_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(detect_person_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(detect_person_TEST_DEPENDS )
set(detect_person_DOC_DEPENDS )
set(detect_person_URL_WEBSITE "")
set(detect_person_URL_BUGTRACKER "")
set(detect_person_URL_REPOSITORY "")
set(detect_person_DEPRECATED "")